const BASE_1 = "#1E1E1E";
const BASE_2 = "#767676";
const BASE_3 = "#EDEDED";

const PRIMARY_GREEN_DARK = "#B1C500";
const PRIMARY_GREEN = "#E2F070";
const PRIMARY_GREEN_LIGHT = "#EDF798";
const PRIMARY_PINK_DARK = "#FF7989";
const PRIMARY_PINK_LIGHT = "#FFD6DB";

export {
  BASE_1,
  BASE_2,
  BASE_3,
  PRIMARY_GREEN_DARK,
  PRIMARY_GREEN,
  PRIMARY_GREEN_LIGHT,
  PRIMARY_PINK_DARK,
  PRIMARY_PINK_LIGHT,
};
