import { ImageSourcePropType } from 'react-native';
import { avatarDecorationCategories } from './decoration';

const avatarItemList = [
  'avatar1-hair-black-female',
  'avatar1-hair-brown-female',
  'avatar1-hair-green-female',
  'avatar1-hair-pink-female',
  'avatar1-hair-black-male',
  'avatar1-hair-brown-male',
  'avatar1-hair-green-male',
  'avatar1-hair-pink-male',
  'avatar1-tops',
  'avatar1-bottoms-female',
  'avatar1-bottoms-male',
  'avatar1-shoes-female',
  'avatar1-shoes-male',
  'avatar2-hair-black-female',
  'avatar2-hair-brown-female',
  'avatar2-hair-green-female',
  'avatar2-hair-pink-female',
  'avatar2-hair-black-male',
  'avatar2-hair-brown-male',
  'avatar2-hair-green-male',
  'avatar2-hair-pink-male',
  'avatar2-tops-female',
  'avatar2-tops-male',
  'avatar2-bottoms-female',
  'avatar2-bottoms-male',
  'avatar2-shoes-female',
  'avatar2-shoes-male',
  'avatar3-hair-black-female',
  'avatar3-hair-brown-female',
  'avatar3-hair-green-female',
  'avatar3-hair-pink-female',
  'avatar3-hair-black-male',
  'avatar3-hair-brown-male',
  'avatar3-hair-green-male',
  'avatar3-hair-pink-male',
  'avatar3-tops-female',
  'avatar3-tops-male',
  'avatar3-bottoms-female',
  'avatar3-bottoms-male',
  'avatar3-shoes-female',
  'avatar3-shoes-male',
] as const;

type AvatarItem = {
  id: number;
  name: (typeof avatarItemList)[number];
  price: number;
  image: ImageSourcePropType;
  category: (typeof avatarDecorationCategories)[number];
};

const avatarItems: AvatarItem[] = [
  {
    id: 1,
    name: 'avatar1-hair-black-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar1-hair-black-female.png'),
    category: '헤어',
  },
  {
    id: 2,
    name: 'avatar1-hair-brown-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar1-hair-brown-female.png'),
    category: '헤어',
  },
  {
    id: 3,
    name: 'avatar1-hair-green-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar1-hair-green-female.png'),
    category: '헤어',
  },
  {
    id: 4,
    name: 'avatar1-hair-pink-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar1-hair-pink-female.png'),
    category: '헤어',
  },
  {
    id: 5,
    name: 'avatar1-hair-black-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar1-hair-black-male.png'),
    category: '헤어',
  },
  {
    id: 6,
    name: 'avatar1-hair-brown-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar1-hair-brown-male.png'),
    category: '헤어',
  },
  {
    id: 7,
    name: 'avatar1-hair-green-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar1-hair-green-male.png'),
    category: '헤어',
  },
  {
    id: 8,
    name: 'avatar1-hair-pink-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar1-hair-pink-male.png'),
    category: '헤어',
  },
  {
    id: 9,
    name: 'avatar1-tops',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar1-tops.png'),
    category: '상의',
  },
  {
    id: 10,
    name: 'avatar1-bottoms-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar1-bottoms-female.png'),
    category: '하의',
  },
  {
    id: 11,
    name: 'avatar1-bottoms-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar1-bottoms-male.png'),
    category: '하의',
  },
  {
    id: 12,
    name: 'avatar1-shoes-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar1-shoes-female.png'),
    category: '신발',
  },
  {
    id: 13,
    name: 'avatar1-shoes-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar1-shoes-male.png'),
    category: '신발',
  },
  {
    id: 14,
    name: 'avatar2-hair-black-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar2-hair-black-female.png'),
    category: '헤어',
  },
  {
    id: 15,
    name: 'avatar2-hair-brown-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar2-hair-brown-female.png'),
    category: '헤어',
  },
  {
    id: 16,
    name: 'avatar2-hair-green-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar2-hair-green-female.png'),
    category: '헤어',
  },
  {
    id: 17,
    name: 'avatar2-hair-pink-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar2-hair-pink-female.png'),
    category: '헤어',
  },
  {
    id: 18,
    name: 'avatar2-hair-black-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar2-hair-black-male.png'),
    category: '헤어',
  },
  {
    id: 19,
    name: 'avatar2-hair-brown-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar2-hair-brown-male.png'),
    category: '헤어',
  },
  {
    id: 20,
    name: 'avatar2-hair-green-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar2-hair-green-male.png'),
    category: '헤어',
  },
  {
    id: 21,
    name: 'avatar2-hair-pink-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar2-hair-pink-male.png'),
    category: '헤어',
  },
  {
    id: 22,
    name: 'avatar2-tops-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar2-tops-female.png'),
    category: '상의',
  },
  {
    id: 23,
    name: 'avatar2-tops-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar2-tops-male.png'),
    category: '상의',
  },
  {
    id: 24,
    name: 'avatar2-bottoms-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar2-bottoms-female.png'),
    category: '하의',
  },
  {
    id: 25,
    name: 'avatar2-bottoms-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar2-bottoms-male.png'),
    category: '하의',
  },
  {
    id: 26,
    name: 'avatar2-shoes-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar2-shoes-female.png'),
    category: '신발',
  },
  {
    id: 27,
    name: 'avatar2-shoes-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar2-shoes-male.png'),
    category: '신발',
  },
  {
    id: 28,
    name: 'avatar3-hair-black-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar3-hair-black-female.png'),
    category: '헤어',
  },
  {
    id: 29,
    name: 'avatar3-hair-brown-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar3-hair-brown-female.png'),
    category: '헤어',
  },
  {
    id: 30,
    name: 'avatar3-hair-green-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar3-hair-green-female.png'),
    category: '헤어',
  },
  {
    id: 31,
    name: 'avatar3-hair-pink-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar3-hair-pink-female.png'),
    category: '헤어',
  },
  {
    id: 32,
    name: 'avatar3-hair-black-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar3-hair-black-male.png'),
    category: '헤어',
  },
  {
    id: 33,
    name: 'avatar3-hair-brown-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar3-hair-brown-male.png'),
    category: '헤어',
  },
  {
    id: 34,
    name: 'avatar3-hair-green-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar3-hair-green-male.png'),
    category: '헤어',
  },
  {
    id: 35,
    name: 'avatar3-hair-pink-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar3-hair-pink-male.png'),
    category: '헤어',
  },
  {
    id: 36,
    name: 'avatar3-tops-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar3-tops-female.png'),
    category: '상의',
  },
  {
    id: 37,
    name: 'avatar3-tops-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar3-tops-male.png'),
    category: '상의',
  },
  {
    id: 38,
    name: 'avatar3-bottoms-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar3-bottoms-female.png'),
    category: '하의',
  },
  {
    id: 39,
    name: 'avatar3-bottoms-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar3-bottoms-male.png'),
    category: '하의',
  },
  {
    id: 40,
    name: 'avatar3-shoes-female',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar3-shoes-female.png'),
    category: '신발',
  },
  {
    id: 41,
    name: 'avatar3-shoes-male',
    price: 0,
    image: require('@/src/shared/assets/images/avatar-items/avatar3-shoes-male.png'),
    category: '신발',
  },
];
export { avatarItems, AvatarItem, avatarItemList };
